# SPDX-FileCopyrightText: 2021 Andreas Schmidt <andreas.schmidt@iese.fraunhofer.de>
#
# SPDX-License-Identifier: CC0-1.0

[book]
authors = ["Andreas Schmidt"]
language = "en"
multilingual = false
src = "src"
title = "Opus: The Book of ConSerts"

[output.html]
git-repository-url = "https://erbenschell.iese.fraunhofer.de/real-time-conserts/opus"
git-repository-icon = "fa-gitlab"
mathjax-support = true
additional-css = ["custom.css"]

[output.linkcheck]
exclude = [ 'safetbox\.de', 'crates\.io', 'kit\.edu' , 'doi\.org']

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = true